[package]
name = "havok-repl"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[dependencies]
colored = "2.0.0"
rustyline = "11.0.0"
rustyline-derive = "0.8.0"
termimad = "0.23.0"

[dependencies.havok-lib]
path = "../havok-lib"
